on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
        - dev
  
jobs:
    setup-and-run:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
  
        - name: Install Aztec CLI
          run: |
            curl -s https://install.aztec.network > tmp.sh
            bash tmp.sh <<< yes "yes"
  
        - name: Update path
          run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH

        - name: Fetch latest Aztec version
          run: |
            RAW_VERSION=$(node ./.github/scripts/fetchRelease.js)
            AZTEC_VERSION=$(echo "$RAW_VERSION" | sed 's/aztec-packages-v//')
            echo "AZTEC_VERSION=$AZTEC_VERSION" >> "$GITHUB_ENV"
  
        - name: Set Aztec version and start sandbox
          run: |
            echo "Using Aztec version: $AZTEC_VERSION"
            VERSION=$AZTEC_VERSION aztec-up
            aztec start --sandbox &
  
        - name: Install project dependencies
          run: yarn
  
        - name: Compile
          run: script -e -c "${AZTEC_NARGO:-aztec-nargo} compile"
  
        - name: Codegen
          run: script -e -c "aztec codegen target --outdir src/artifacts"
  
        - name: Run tests
          run: script -e -c "NODE_NO_WARNINGS=1 node --experimental-vm-modules $(yarn bin jest) --no-cache --runInBand --config jest.integration.config.json && aztec test"
  